# Version 2

language: c
sudo: false

script:
  make-kpkg --jobs 4 --rootcmd fakeroot --arch armhf --cross-compile arm-linux-gnueabihf- --initrd --append-to-version=-wm --revision=$TRAVIS_JOB_NUMBER kernel_image

addons:
  apt:
    packages:
      - build-essential
      # Unfortunately, "gcc-arm-linux-gnueabihf" is not allowed
      # directly, so resort to an allowed package with version prefix
      #- gcc-arm-linux-gnueabihf
      - gcc-4.6-arm-linux-gnueabihf
      # for make-kpkg
      - kernel-package
      # required for kernel-package
      - fakeroot
