# Version 2

language: c
sudo: false

script:
  make -j deb-pkg ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- "LOCALVERSION=wb$TRAVIS_JOB_NUMBER"

addons:
  apt:
    packages:
      - build-essential
      # Unfortunately, "gcc-arm-linux-gnueabihf" is not allowed
      # directly, so resort to an allowed package with version prefix
      #- gcc-arm-linux-gnueabihf
      - gcc-4.6-arm-linux-gnueabihf
      # required for kernel-package
      - fakeroot
