# Version 2

language: c
sudo: false

before_script:
  # Set up proper symlinks
  - mkdir -p "$HOME/bin"
  - ln -s /usr/bin/arm-linux-gnueabihf-gcc-4.6 "$HOME/bin/arm-linux-gnueabihf-gcc"

  - export PATH="$HOME/bin:$PATH"

script:
  make deb-pkg ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- "LOCALVERSION=wb$TRAVIS_JOB_NUMBER"

addons:
  apt:
    packages:
      - build-essential
      - bc
      # Unfortunately, "gcc-arm-linux-gnueabihf" is not allowed
      # directly, so resort to an allowed package with version prefix
      #- gcc-arm-linux-gnueabihf
      - gcc-4.6-arm-linux-gnueabihf
      # required for kernel-package
      - fakeroot
